name: Deploy Assets to WordPress.org

on:
  push:
    branches:
      - main
    paths:
      - '.wordpress-org/**'
  workflow_dispatch:

jobs:
  assets:
    name: Deploy Plugin Assets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: 10up/action-wordpress-plugin-asset-update@stable
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SLUG: thegridindex-rss-importer
